增加了一些启动器的api
UIGF-org/mihoyo-api-collect pull request #22
Opened 2023-08-20 13:36 UTC by moyanj

增加了一些启动器的api

2023-08-20 22:45 UTC, Kamisato-Ayaka-233 requested changes

2023-08-20 22:45 UTC, Kamisato-Ayaka-233 commented on other/id.md
> +| 17 | 原神(B服) | KAtdSsoQ |
最好将第2列移至第1列

2023-08-20 22:45 UTC, Kamisato-Ayaka-233 commented on other/launcher.md
> +| bg_checksum | str | 背景图哈希值 | 可能是md5 |
描述错误，不应为“哈希值”，而是“校验码”

2023-08-20 22:45 UTC, Kamisato-Ayaka-233 commented on other/launcher.md
> +| links | list | 链接列表 | 可能为空 |
数据类型错误，应为`arr`

2023-08-20 22:45 UTC, Kamisato-Ayaka-233 commented on other/launcher.md
> +都说了未知了。
若未知对象与数组的值，则不应在下文指出该对象或数组。因此应该将这段删除

2023-08-20 22:45 UTC, Kamisato-Ayaka-233 commented on other/launcher.md
> +| launcher_id | num | 启动器id | |
最好将`key`改为`Key`，`id`改为`ID`

2023-08-20 22:45 UTC, Kamisato-Ayaka-233 commented on other/launcher.md
> +| data | obj | 玩家信息 | |
根据下文，该字段的内容不应为“玩家信息”。

2023-08-20 22:45 UTC, Kamisato-Ayaka-233 commented on other/launcher.md
> +同：`data`对象→`game`对象→`deprecated_packages`数组→对象：
应改为：
```
与`data`对象→`game`对象→`deprecated_packages`数组→对象中的结构相同
```

2023-08-22 00:46 UTC, moyanj commented on launcher/sr.md
> +`adv`对象：
该文件已在最新commit删除

2023-08-22 00:46 UTC, moyanj commented on launcher/sr.md
> +| bg_checksum | str | 背景图哈希值 | 可能是md5 |
该文件已在最新commit删除

2023-08-22 00:59 UTC, moyanj commented
已修改完毕

2023-08-22 03:56 UTC, merged